/**
 * ══════════════════════════════════════════════════════════════════════════
 *  REGENERATE THE COMMITTED FIXTURES — A DELIBERATE ACT, NEVER AUTOMATIC
 * ══════════════════════════════════════════════════════════════════════════
 *
 * `npm run fixtures:refresh`, and it needs a Monospace checkout because the
 * reference `.xlsx` files are generated by MONOSPACE'S OWN WRITER.
 *
 * ⚠️ IT MUST NOT BE WIRED INTO `test` OR `build`. A fixture that regenerates
 * itself before every comparison compares a file to itself and passes forever.
 * The point of committing the bytes is that changing them shows up in a diff
 * and somebody has to say why.
 *
 * What it writes:
 *
 *   fixtures/school.fixture.json      the input, so the format has a worked
 *                                     example that is checked by being used
 *   fixtures/reference-full.xlsx      all four options on, with a password
 *   fixtures/reference-plain.xlsx     every option off
 *   fixtures/palette.txt              ⭐ every class code → its hex
 *
 * ── ⭐ WHY THE PALETTE IS ITS OWN FIXTURE ────────────────────────────────
 * `colourForClass()` is a gamut bisection inside a lightness bisection over
 * 485 float literals whose own rule is "measure, never reason from the
 * constants". Three separate claims about that palette have failed
 * measurement. A text file of code → hex means any change to it is a DIFF
 * somebody has to look at, rather than a colour quietly moving in every
 * school's workbook.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildTimetableModel } from "../src/model/buildModel";
import { colourForClass, compareClassCodes } from "../src/lib/timetableSheet";
import {
  FIXTURE_NOW,
  FIXTURE_PASSWORD,
  makeFixtureDocument,
  makeFixtureDocumentPlain,
} from "../test/fixtures/schoolDocument";
import { haveMonospaceSource, monospaceRoot, referenceWorkbook } from "../gate/reference";

const OUT = resolve(fileURLToPath(new URL("..", import.meta.url)), "fixtures");

/**
 * ⭐ EVERY CLASS CODE THE FIXTURE DRAWS, PLUS THE EDGE CASES THAT MUST GET NO
 * COLOUR AT ALL. A palette fixture listing only the codes that DO colour would
 * not notice `colourForClass` starting to colour "Booked".
 */
const PALETTE_PROBES = [
  "7A/Cs", "7B/Cs", "8C/Bs", "8D/It", "9E/It", "9F/It",
  "10D/Bs", "10E/Cs", "11B/It", "11C/Bs", "12/Cs1", "13/It2",
  /* ⚠️ THESE MUST COME BACK null. A free-text booking, the withheld-purpose
     substitution, a typed "-" and an empty string name no class. */
  "Staff briefing", "Booked", "-", "", "Code Club",
  "GCSE speaking exams", "Mock exam",
  /* Shapes the rule has to keep answering the same way. */
  "7A", "13B/Ph1", "10x/Ma3", "9F/It ", "  9F/It",
];

function palette(): string {
  const lines = [
    "# Every class code → the fill colour colourForClass() derives for it.",
    "#",
    "# ⚠️ A DIFF HERE IS A COLOUR CHANGING IN EVERY SCHOOL'S WORKBOOK. The",
    "# palette is a gamut bisection inside a lightness bisection and its own",
    "# rule is 'measure, never reason from the constants' — so it is pinned",
    "# here as measured output rather than trusted as arithmetic.",
    "#",
    "# `-` in the colour column means the string names no class and gets no",
    "# fill, which is as load-bearing as any of the hexes: a free-text booking",
    "# and the withheld-purpose word 'Booked' must never be coloured.",
    "#",
    "# Regenerate with `npm run fixtures:refresh`.",
    "",
  ];
  for (const code of [...PALETTE_PROBES].sort(compareClassCodes)) {
    const argb = colourForClass(code);
    lines.push(`${JSON.stringify(code)}\t${argb ?? "-"}`);
  }
  return lines.join("\n") + "\n";
}

async function main() {
  mkdirSync(OUT, { recursive: true });

  const doc = makeFixtureDocument();
  writeFileSync(
    resolve(OUT, "school.fixture.json"),
    JSON.stringify(doc, null, 2) + "\n",
  );
  writeFileSync(resolve(OUT, "palette.txt"), palette());
  console.log("wrote school.fixture.json and palette.txt");

  if (!haveMonospaceSource()) {
    console.error(
      `\n⚠️  No Monospace checkout at ${monospaceRoot()} — the reference .xlsx files were NOT refreshed.\n` +
        `    Set MONOSPACE_SOURCE to the checkout and run again. The gate needs them to have been\n` +
        `    generated by Monospace's writer; generating them with ours would compare a file to itself.`,
    );
    process.exitCode = 1;
    return;
  }

  const cases: Array<[string, ReturnType<typeof makeFixtureDocument>, string | undefined]> = [
    ["reference-full.xlsx", doc, FIXTURE_PASSWORD],
    ["reference-plain.xlsx", makeFixtureDocumentPlain(), undefined],
  ];

  for (const [name, document, password] of cases) {
    const built = buildTimetableModel({
      document,
      now: FIXTURE_NOW,
      generatedBy: "Fixture",
      password,
    });
    if (!built.ok) throw new Error(`${name}: ${built.error}`);
    const bytes = await referenceWorkbook(built.model);
    writeFileSync(resolve(OUT, name), bytes);
    console.log(`wrote ${name} (${bytes.length} bytes) from Monospace's writer`);
  }
}

await main();
