/**
 * ══════════════════════════════════════════════════════════════════════════
 *  ⭐⭐ THE FIXTURE GATE
 * ══════════════════════════════════════════════════════════════════════════
 *
 * The one claim this package has to earn: **our writer produces the same bytes
 * Monospace's does.** Not "an equivalent workbook", not "the same content" —
 * the same bytes, member by member, at the same compression, in the same
 * order, with exactly three normalisations that are each argued for in
 * `zip.ts`.
 *
 * ⚠️ THE WEAKER VERSIONS OF THIS TEST ARE THE TEMPTING ONES. "Open both in
 * exceljs and compare cell values" passes when the styles diverge. "Diff the
 * unzipped XML" passes when the compression level changes, which is how a
 * dependency swapping its zip backend gets into a release. So the comparison
 * is on the RAW COMPRESSED BYTES, and a member that had to be normalised is
 * compared as normalised TEXT plus its compression method — never skipped.
 *
 * ── WHAT IS COMPARED AGAINST WHAT ────────────────────────────────────────
 *   · `fixtures/reference-*.xlsx` are COMMITTED and were generated by
 *     Monospace's own writer (`npm run fixtures:refresh`). Every run compares
 *     against them, on any machine, with no Monospace checkout needed.
 *   · When a checkout IS present, one more test regenerates the reference LIVE
 *     and compares that too — so a fixture that has gone stale against the
 *     product it mirrors is caught rather than trusted.
 */

import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, test } from "vitest";

import { buildTimetableModel } from "../src/model/buildModel";
import { bufferTimetableWorkbook } from "../src/workbook/timetableWorkbook";
import { colourForClass, compareClassCodes } from "../src/lib/timetableSheet";
import {
  FIXTURE_NOW,
  FIXTURE_PASSWORD,
  makeFixtureDocument,
  makeFixtureDocumentPlain,
} from "./fixtures/schoolDocument";
import { haveMonospaceSource, referenceWorkbook } from "./reference";
import { bytesEqual, readZip, stripVolatile, VOLATILE, type ZipMember } from "./zip";
import { sequenceViolations } from "./ctWorksheet";

const FIXTURES = resolve(fileURLToPath(new URL("..", import.meta.url)), "fixtures");

type Case = {
  label: string;
  fixture: string;
  document: ReturnType<typeof makeFixtureDocument>;
  password: string | undefined;
};

const CASES: Case[] = [
  {
    /* All four options on, with a password: formulas, conditional formatting,
       hidden tabs, SHA-512 sheet protection and the `sheetProtection` hoist on
       every grid sheet. */
    label: "every option on, with a password",
    fixture: "reference-full.xlsx",
    document: makeFixtureDocument(),
    password: FIXTURE_PASSWORD,
  },
  {
    /* ⭐ A DIFFERENT WRITER PATH, not a smaller one: no `protect()`, so no
       salt, no hash and the hoist never runs; no formulas; no conditional
       formatting. It is also the file most schools will actually get. */
    label: "every option off",
    fixture: "reference-plain.xlsx",
    document: makeFixtureDocumentPlain(),
    password: undefined,
  },
];

function ourBytes(c: Case): Promise<Uint8Array> {
  const built = buildTimetableModel({
    document: c.document,
    now: FIXTURE_NOW,
    generatedBy: "Fixture",
    password: c.password,
  });
  if (!built.ok) throw new Error(built.error);
  return bufferTimetableWorkbook(built.model);
}

type Report = {
  members: number;
  identicalRaw: number;
  identicalNormalised: number;
  normalisedMembers: string[];
  substitutions: Record<string, number>;
};

/**
 * The comparison, and the whole of it.
 *
 * ⚠️ IT FAILS ON THE FIRST DIFFERENCE **WITH THE MEMBER NAMED**, because
 * "two files differ" is not an actionable failure for a 50-part zip.
 */
function compare(ours: Uint8Array, reference: Uint8Array): Report {
  const a = readZip(reference);
  const b = readZip(ours);

  expect(b.map((m) => m.name), "the set and ORDER of zip members").toEqual(
    a.map((m) => m.name),
  );

  const report: Report = {
    members: a.length,
    identicalRaw: 0,
    identicalNormalised: 0,
    normalisedMembers: [],
    substitutions: {},
  };

  for (let i = 0; i < a.length; i++) {
    const ref: ZipMember = a[i];
    const our: ZipMember = b[i];

    /* The fast, strict path: the member's stored bytes are identical. This is
       what catches a compression-level change, and it is where all but a
       handful of members land. */
    if (
      ref.method === our.method &&
      ref.crc32 === our.crc32 &&
      ref.compressedSize === our.compressedSize &&
      ref.uncompressedSize === our.uncompressedSize &&
      bytesEqual(ref.compressed, our.compressed)
    ) {
      report.identicalRaw++;
      continue;
    }

    /* Otherwise the ONLY acceptable explanation is one of the three volatile
       fields. Normalise both and require the results to match exactly. */
    const sr = stripVolatile(ref.content);
    const so = stripVolatile(our.content);

    /* ⚠️ THE SUBSTITUTION COUNTS ARE COMPARED TOO. Without this, a file that
       stopped writing `saltValue` altogether would pass as "normalised" — the
       pattern simply would not match, on both sides, and the texts would
       agree about a protection attribute that is no longer there. */
    expect(so.hits, `${our.name}: number of volatile substitutions`).toEqual(
      sr.hits,
    );

    const changed = sr.hits.some((n) => n > 0);
    if (!changed) {
      /* Bytes differ and nothing volatile is in this member. That is the
         regression this gate exists for. */
      const at = firstTextDifference(sr.text, so.text);
      throw new Error(
        `${our.name} differs from the reference and contains none of the three volatile fields.\n` +
          `  reference: ${ref.compressedSize} compressed / ${ref.uncompressedSize} raw, method ${ref.method}, crc ${ref.crc32}\n` +
          `  ours     : ${our.compressedSize} compressed / ${our.uncompressedSize} raw, method ${our.method}, crc ${our.crc32}\n` +
          (at === null
            ? "  (identical text — so the difference is the COMPRESSION itself, which is a regression in its own right)"
            : `  first difference at character ${at}:\n` +
              `    reference … ${JSON.stringify(sr.text.slice(Math.max(0, at - 60), at + 60))}\n` +
              `    ours      … ${JSON.stringify(so.text.slice(Math.max(0, at - 60), at + 60))}`),
      );
    }

    expect(so.text, `${our.name}, normalised`).toEqual(sr.text);
    /* Compression method still has to agree even for a normalised member —
       only the CONTENT was allowed to move, not how it is stored. */
    expect(our.method, `${our.name}: compression method`).toBe(ref.method);

    report.identicalNormalised++;
    report.normalisedMembers.push(our.name);
    VOLATILE.forEach((v, k) => {
      if (sr.hits[k] > 0) {
        report.substitutions[v.why] =
          (report.substitutions[v.why] ?? 0) + sr.hits[k];
      }
    });
  }
  return report;
}

function firstTextDifference(a: string, b: string): number | null {
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i++) if (a[i] !== b[i]) return i;
  return a.length === b.length ? null : n;
}

describe("the fixture gate", () => {
  for (const c of CASES) {
    test(`byte-identical to Monospace's writer — ${c.label}`, async () => {
      const referencePath = resolve(FIXTURES, c.fixture);
      expect(
        existsSync(referencePath),
        `${c.fixture} is missing. Run \`npm run fixtures:refresh\` with a Monospace checkout.`,
      ).toBe(true);

      const reference = new Uint8Array(readFileSync(referencePath));
      const ours = await ourBytes(c);
      const report = compare(ours, reference);

      /* ⭐ THE NUMBERS, PRINTED. A gate whose result is only "passed" tells
         you nothing about what it actually checked. */
      console.log(
        `\n  ${c.label}\n` +
          `    zip members compared        ${report.members}\n` +
          `    identical raw compressed    ${report.identicalRaw}\n` +
          `    identical after normalising ${report.identicalNormalised}` +
          (report.normalisedMembers.length
            ? ` (${report.normalisedMembers.join(", ")})`
            : "") +
          `\n` +
          Object.entries(report.substitutions)
            .map(([why, n]) => `    ${n} × ${why}\n`)
            .join("") +
          `    reference bytes             ${reference.length}\n` +
          `    our bytes                   ${ours.length}`,
      );

      expect(report.identicalRaw + report.identicalNormalised).toBe(
        report.members,
      );
    });
  }

  /**
   * ⚠️ THE COMMITTED FIXTURE COULD BE STALE — it is a snapshot of a product
   * that is still being worked on. When a Monospace checkout is here, the
   * reference is regenerated live and compared, so "the fixture matches" and
   * "the product matches" cannot quietly become different claims.
   */
  test.skipIf(!haveMonospaceSource())(
    "the committed fixtures still match Monospace's writer today",
    async () => {
      for (const c of CASES) {
        const built = buildTimetableModel({
          document: c.document,
          now: FIXTURE_NOW,
          generatedBy: "Fixture",
          password: c.password,
        });
        if (!built.ok) throw new Error(built.error);
        const live = await referenceWorkbook(built.model);
        const committed = new Uint8Array(
          readFileSync(resolve(FIXTURES, c.fixture)),
        );
        const report = compare(live, committed);
        console.log(
          `\n  live vs committed — ${c.label}: ${report.identicalRaw} raw + ${report.identicalNormalised} normalised of ${report.members}`,
        );
        expect(report.identicalRaw + report.identicalNormalised).toBe(
          report.members,
        );
      }
    },
  );
});

describe("the palette", () => {
  /**
   * ⭐ EVERY CLASS CODE → ITS HEX, PINNED AS TEXT.
   *
   * `colourForClass()` is a gamut bisection inside a lightness bisection over
   * a few hundred float literals whose own rule is "measure, never reason from
   * the constants". Three separate claims about that palette have failed
   * measurement. Pinning the OUTPUT means any change is a diff somebody has to
   * look at, rather than a colour quietly moving in every school's workbook.
   */
  test("matches fixtures/palette.txt exactly", () => {
    const text = readFileSync(resolve(FIXTURES, "palette.txt"), "utf8");
    const rows = text
      .split("\n")
      .filter((l) => l.trim() && !l.startsWith("#"))
      .map((l) => {
        const [code, argb] = l.split("\t");
        return { code: JSON.parse(code) as string, argb };
      });

    expect(rows.length, "the palette fixture has rows in it").toBeGreaterThan(20);

    /* Sorted with the workbook's own comparator, so the fixture's ORDER is
       part of what is pinned — `compareClassCodes` decides the legend's order
       on the info sheet. */
    const sorted = [...rows].sort((a, b) => compareClassCodes(a.code, b.code));
    expect(sorted.map((r) => r.code)).toEqual(rows.map((r) => r.code));

    for (const { code, argb } of rows) {
      expect(colourForClass(code) ?? "-", `colourForClass(${JSON.stringify(code)})`).toBe(argb);
    }

    /* ⚠️ THE `-` ROWS ARE AS LOAD-BEARING AS THE HEXES. A free-text booking,
       the withheld-purpose word "Booked" and a typed "-" must never be
       coloured; a palette fixture listing only the codes that DO colour would
       not notice `colourForClass` starting to colour them. */
    expect(
      rows.filter((r) => r.argb === "-").length,
      "strings that must get no fill at all",
    ).toBeGreaterThan(4);
  });
});

describe("what the workbook is made of", () => {
  /**
   * ⚠️ `CT_Worksheet` IS AN `xsd:sequence`. An element out of place is the
   * "we found a problem with some content" repair prompt, and a repair drops
   * what it could not place — so for a workbook whose whole point is
   * protection, it opens unprotected or not at all.
   *
   * ⭐ `hoist.test.ts` proves THIS check works by turning the hoist off and
   * requiring it to fail. A validator nobody has seen fail is untested.
   */
  test("every sheet part obeys the CT_Worksheet element sequence", async () => {
    let sheets = 0;
    let elements = 0;
    for (const c of CASES) {
      const members = readZip(await ourBytes(c));
      for (const m of members) {
        if (!/^xl\/worksheets\/sheet\d+\.xml$/.test(m.name)) continue;
        sheets++;
        const xml = new TextDecoder().decode(m.content);
        const bad = sequenceViolations(m.name, xml);
        elements += bad.length;
        expect(
          bad,
          `${c.label} — ${m.name}:\n${bad.map((v) => "  " + v.message).join("\n")}`,
        ).toEqual([]);
      }
    }
    console.log(
      `\n  CT_Worksheet sequence: ${sheets} sheet parts checked, ${elements} violations`,
    );
    /* Both fixtures together: 2 templates + 39 weeks + half terms + info,
       twice over. Asserted so a fixture that silently stopped producing sheets
       cannot pass this test by checking nothing. */
    expect(sheets).toBeGreaterThan(80);
  });

  /**
   * ⚠️ THE STUB THAT LETS THE REFERENCE LOAD MUST NOT BE LOAD-BEARING FOR US.
   * `server-only` is aliased so Monospace's unmodified writer can be imported
   * — documented change #1 is that OUR writer does not have that import. If it
   * ever came back, the gate would still pass while the browser build broke,
   * because vitest would resolve it and a bundler would not.
   */
  test("nothing in src/ imports server-only", () => {
    const walk = (dir: string): string[] => {
      const { readdirSync, statSync } = require("node:fs") as typeof import("node:fs");
      return readdirSync(dir).flatMap((entry: string) => {
        const full = resolve(dir, entry);
        return statSync(full).isDirectory() ? walk(full) : [full];
      });
    };
    const src = resolve(fileURLToPath(new URL("..", import.meta.url)), "src");
    /* ⚠️ AN IMPORT, NOT THE WORDS. Two files under src/ DISCUSS `server-only`
       in their banners — the spec explains why it is pure, and the writer
       documents removing it — and a substring test would fail on the very
       comments that record the decision. It is the statement that must not
       come back. */
    const IMPORT = /(?:^|\n)\s*(?:import\s+["']server-only["']|import\s[^\n;]*from\s+["']server-only["']|require\(\s*["']server-only["']\s*\))/;
    const offenders = walk(src).filter(
      (f) => f.endsWith(".ts") && IMPORT.test(readFileSync(f, "utf8")),
    );
    expect(offenders, "files under src/ importing server-only").toEqual([]);
  });

  /**
   * ⚠️ AND THE BARREL MUST NOT COME BACK EITHER. `import ExcelJS from "exceljs"`
   * as a VALUE resolves, in a browser bundle, to `dist/exceljs.min.js` — which
   * has no `stream` namespace at all — and drags in the reader, unzipper and
   * bluebird, which crashes on `process.versions`. Documented change #3.
   */
  test("the writer imports exceljs only as a type and by deep specifier", () => {
    const writer = readFileSync(
      resolve(fileURLToPath(new URL("..", import.meta.url)), "src/workbook/timetableWorkbook.ts"),
      "utf8",
    );
    expect(writer).toContain('import type ExcelJS from "exceljs"');
    expect(writer).toContain(
      'import WorkbookWriter from "exceljs/lib/stream/xlsx/workbook-writer.js"',
    );
    /* A value import of the barrel would look exactly like the type one minus
       the keyword, so it is tested for by absence. */
    expect(writer).not.toMatch(/^import ExcelJS from "exceljs"/m);
    /* ⭐ AND NO SECOND WRITER, EVER. The buffered `ExcelJS.Workbook` silently
       ignores `useSharedStrings: false` and differs in 47 of 50 zip parts. */
    expect(writer).not.toMatch(/new ExcelJS\.Workbook\b/);
  });

  /** ⚠️ `node:stream` is the one line that cannot run in a browser. It belongs
   *  in `stream.ts` and nowhere else, so the `browser` field can swap it. */
  test("node:stream appears only in the Node half of the stream port", () => {
    const walk = (dir: string): string[] => {
      const { readdirSync, statSync } = require("node:fs") as typeof import("node:fs");
      return readdirSync(dir).flatMap((entry: string) => {
        const full = resolve(dir, entry);
        return statSync(full).isDirectory() ? walk(full) : [full];
      });
    };
    const src = resolve(fileURLToPath(new URL("..", import.meta.url)), "src");
    const offenders = walk(src).filter(
      (f) =>
        f.endsWith(".ts") &&
        !f.endsWith("/workbook/stream.ts") &&
        /["']node:(stream|fs|path|zlib|crypto)["']/.test(readFileSync(f, "utf8")),
    );
    expect(offenders, "files under src/ importing a node: builtin").toEqual([]);
  });
});
